version: '3.8'

services:
  # Laravel uchun PHP va Apache konteyneri
  laravel:
    build: .
    container_name: laravel-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  # PostgreSQL ma'lumotlar bazasi
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - laravel-network

volumes:
  db-data:

networks:
  laravel-network:
    driver: bridge
